### ISSUE TITLE
Suggest  adding a UI for XHProf reports to your library

### ISSUE THREAD

**Issue by fh32000** [laracraft-tech/laravel-xhprof#12]
Dear developers of laravel-xhprof,

I am a user of your library and I appreciate the work you have put into creating this valuable tool for profiling Laravel applications. I have noticed that the library currently does not include a user interface for viewing XHProf reports. Instead, users need to download and configure the UI separately.

I would like to suggest that you consider adding a UI for XHProf reports to your library. One possible UI that could be included is the one available at [git@github.com](mailto:git@github.com):preinheimer/xhprof.git.

Including a UI in your library would make it much easier for users to get up and running with XHProf. It would also streamline the configuration process, as users would not need to manually add configuration files to their Laravel installation.

Thank you for considering my suggestion. I look forward to seeing how your library continues to evolve and improve in the future.

Best regards,

[fh32000]

**Comment by Sairahcaz** [comment]
Hi @fh32000,

I don't really get you :D 

In section [Install the UI](https://github.com/laracraft-tech/laravel-xhprof#install-the-ui) we exactly do what you describe...
And in the [Usage](https://github.com/laracraft-tech/laravel-xhprof#usage) section it is described how to use the GUI.

Consider to read the full docs!

**Comment by mihaileu** [comment]
I can say that there's too much steps in order to configure it and make it running. Probably it will be easier if somehow the UI to be embedded and used as a package. Currently the process of following all the steps is long.

**Comment by Sairahcaz** [comment]
@mihaileu when I have more time I'll maybe add a own, buildin GUI to the package.
I already started working on this in branch 2.x, but it's a lot of work :D

**Comment by mihaileu** [comment]
I took a look in main branch, why not add this login in telescope as an option as the codebase is mostly the same?
