### ISSUE TITLE
sudo: add-apt-repository: command not found

### ISSUE THREAD

**Issue by drewgallagher** [laracraft-tech/laravel-xhprof#14]
When trying to install the extension, I get the following error on Mac OS Monterey

```
➜  ~ sudo add-apt-repository ppa:ondrej/php

Password:
sudo: add-apt-repository: command not found
➜  ~ 


```

**Comment by Sairahcaz** [comment]
Hi @drewgallagher you can't use `add-apt-repository` on Mac since it's a Linux/Ubuntu command.
I guess you have to use Homebrew for that. You may try: `brew install php-xhprof`
