### ISSUE TITLE
You do not have permission to view this page.

### ISSUE THREAD

**Issue by andrew-bannister** [laracraft-tech/laravel-xhprof#19]
Hello, 
I have followed the installation instructions, as posted on the front page of this repo, and when I visit '*my app*/vendor/xhprof/xhprof_html/' I am greeted with the following page:
![image](https://github.com/user-attachments/assets/ec2aceaa-22e3-4860-8eda-f5b01ade4e8b)

What can I do to rectify this?
Thanks

**Comment by Sairahcaz** [comment]
seems like you are getting this error:
https://github.com/preinheimer/xhprof/blob/master/xhprof_html/index.php#L11

Are you testing local? Did you set `$controlIPs` to `false` as described here?:
https://github.com/laracraft-tech/laravel-xhprof?tab=readme-ov-file#config
